### ISSUE TITLE
Doesn't work (linux 64bit) - undefined symbol: _ZN2v816FunctionTemplate3NewEPFNS_6HandleINS_5ValueEEERKNS_9ArgumentsEES3_NS1_INS_9SignatureEEE

### ISSUE THREAD

**Issue by ViktorNova** [charlieroberts/interface.server#2]
I've got node installed, the npm modules, ad nw in the same directory - getting this error when trying to run ./nw for the first time (on linux, with latest version of nw binary from git and node v0.10.20)

```
symbol lookup error: /home/guest/Desktop/BUILD/Interface.Server.js/interface.server/node_modules/ws/build/Release/bufferutil.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPFNS_6HandleINS_5ValueEEERKNS_9ArgumentsEES3_NS1_INS_9SignatureEEE
```

Any idea what I'm missing? I've admittedly never used node.js before but your instructions are very straightforward

Also it's worth noting that neither "git submodule init" and "git submodule update" pulled anything into the interface.js dir, so I cloned it separately

**Comment by ViktorNova** [comment]
Previous attempt was with node compiled from source, I tried it with the 64 bit linux binary from nodejs.org and re-got the packages, and got the same exact symbol lookup error

**Comment by charlieroberts** [comment]
So it seems to be some type of problem with the ws (web socket) module... can you try running some simple ws tests and see if those can compile and run safely?

https://github.com/einaros/ws

**Comment by ViktorNova** [comment]
Forgive my ignorance, I have never used node before an am unfamiliar with how to do this. I've cloned the ws repo you linked to but am unsure where to go from there. Can you point me in the right direction?

EDIT: further googling leads me to believe this is due to the absence of libv8.so anywhere on my system, which I guess on many linux distros is installed as a separate package. As it seems to be nowhere in my repos (Porteus/Slackware) I am building it manually and will report back whether or not this was the missing link

**Comment by ViktorNova** [comment]
Well I got v8 installed and still got the same error. I figured I might need to recompile node with v8 shared libraries enabled,  but it wouldn't compile that way.. (like i said i don't really know what I'm doing with node;) but I did figure out how to run the tests on ws! Here's the results of the tests that failed (run as root from the global node_modules directory):

```
  181 passing (7 seconds)
  5 failing

  1) WebSocket ssl can connect to secure websocket server:
     Uncaught Error: DEPTH_ZERO_SELF_SIGNED_CERT
      at SecurePair.<anonymous> (tls.js:1356:32)
      at SecurePair.EventEmitter.emit (events.js:92:17)
      at SecurePair.maybeInitFinished (tls.js:968:10)
      at CleartextStream.read [as _read] (tls.js:462:15)
      at CleartextStream.Readable.read (_stream_readable.js:320:10)
      at EncryptedStream.write [as _write] (tls.js:366:25)
      at doWrite (_stream_writable.js:221:10)
      at writeOrBuffer (_stream_writable.js:211:5)
      at EncryptedStream.Writable.write (_stream_writable.js:180:11)
      at write (_stream_readable.js:583:24)
      at flow (_stream_readable.js:592:7)
      at Socket.pipeOnReadable (_stream_readable.js:624:5)
      at Socket.EventEmitter.emit (events.js:92:17)
      at emitReadable_ (_stream_readable.js:408:10)
      at emitReadable (_stream_readable.js:404:5)
      at readableAddChunk (_stream_readable.js:165:9)
      at Socket.Readable.push (_stream_readable.js:127:10)
      at TCP.onread (net.js:526:21)

  2) WebSocket ssl can connect to secure websocket server with client side certificate:
     Uncaught Error: DEPTH_ZERO_SELF_SIGNED_CERT
      at SecurePair.<anonymous> (tls.js:1356:32)
      at SecurePair.EventEmitter.emit (events.js:92:17)
      at SecurePair.maybeInitFinished (tls.js:968:10)
      at CleartextStream.read [as _read] (tls.js:462:15)
      at CleartextStream.Readable.read (_stream_readable.js:320:10)
      at EncryptedStream.write [as _write] (tls.js:366:25)
      at doWrite (_stream_writable.js:221:10)
      at writeOrBuffer (_stream_writable.js:211:5)
      at EncryptedStream.Writable.write (_stream_writable.js:180:11)
      at write (_stream_readable.js:583:24)
      at flow (_stream_readable.js:592:7)
      at Socket.pipeOnReadable (_stream_readable.js:624:5)
      at Socket.EventEmitter.emit (events.js:92:17)
      at emitReadable_ (_stream_readable.js:408:10)
      at emitReadable (_stream_readable.js:404:5)
      at readableAddChunk (_stream_readable.js:165:9)
      at Socket.Readable.push (_stream_readable.js:127:10)
      at TCP.onread (net.js:526:21)

  3) WebSocket ssl can send and receive text data:
     Uncaught Error: DEPTH_ZERO_SELF_SIGNED_CERT
      at SecurePair.<anonymous> (tls.js:1356:32)
      at SecurePair.EventEmitter.emit (events.js:92:17)
      at SecurePair.maybeInitFinished (tls.js:968:10)
      at CleartextStream.read [as _read] (tls.js:462:15)
      at CleartextStream.Readable.read (_stream_readable.js:320:10)
      at EncryptedStream.write [as _write] (tls.js:366:25)
      at doWrite (_stream_writable.js:221:10)
      at writeOrBuffer (_stream_writable.js:211:5)
      at EncryptedStream.Writable.write (_stream_writable.js:180:11)
      at write (_stream_readable.js:583:24)
      at flow (_stream_readable.js:592:7)
      at Socket.pipeOnReadable (_stream_readable.js:624:5)
      at Socket.EventEmitter.emit (events.js:92:17)
      at emitReadable_ (_stream_readable.js:408:10)
      at emitReadable (_stream_readable.js:404:5)
      at readableAddChunk (_stream_readable.js:165:9)
      at Socket.Readable.push (_stream_readable.js:127:10)
      at TCP.onread (net.js:526:21)

  4) WebSocket ssl can send and receive very long binary data:
     Uncaught Error: DEPTH_ZERO_SELF_SIGNED_CERT
      at SecurePair.<anonymous> (tls.js:1356:32)
      at SecurePair.EventEmitter.emit (events.js:92:17)
      at SecurePair.maybeInitFinished (tls.js:968:10)
      at CleartextStream.read [as _read] (tls.js:462:15)
      at CleartextStream.Readable.read (_stream_readable.js:320:10)
      at EncryptedStream.write [as _write] (tls.js:366:25)
      at doWrite (_stream_writable.js:221:10)
      at writeOrBuffer (_stream_writable.js:211:5)
      at EncryptedStream.Writable.write (_stream_writable.js:180:11)
      at write (_stream_readable.js:583:24)
      at flow (_stream_readable.js:592:7)
      at Socket.pipeOnReadable (_stream_readable.js:624:5)
      at Socket.EventEmitter.emit (events.js:92:17)
      at emitReadable_ (_stream_readable.js:408:10)
      at emitReadable (_stream_readable.js:404:5)
      at readableAddChunk (_stream_readable.js:165:9)
      at Socket.Readable.push (_stream_readable.js:127:10)
      at TCP.onread (net.js:526:21)

  5) WebSocketServer hybi mode connection establishing verifyClient has secure:true for ssl connections:
     Uncaught Error: DEPTH_ZERO_SELF_SIGNED_CERT
      at SecurePair.<anonymous> (tls.js:1356:32)
      at SecurePair.EventEmitter.emit (events.js:92:17)
      at SecurePair.maybeInitFinished (tls.js:968:10)
      at CleartextStream.read [as _read] (tls.js:462:15)
      at CleartextStream.Readable.read (_stream_readable.js:320:10)
      at EncryptedStream.write [as _write] (tls.js:366:25)
      at doWrite (_stream_writable.js:221:10)
      at writeOrBuffer (_stream_writable.js:211:5)
      at EncryptedStream.Writable.write (_stream_writable.js:180:11)
      at write (_stream_readable.js:583:24)
      at flow (_stream_readable.js:592:7)
      at Socket.pipeOnReadable (_stream_readable.js:624:5)
      at Socket.EventEmitter.emit (events.js:92:17)
      at emitReadable_ (_stream_readable.js:408:10)
      at emitReadable (_stream_readable.js:404:5)
      at readableAddChunk (_stream_readable.js:165:9)
      at Socket.Readable.push (_stream_readable.js:127:10)
      at TCP.onread (net.js:526:21)



make: *** [run-tests] Error 5
```

Not sure if this helps pin it down? 

Apparently there are a LOT of people having this problem, but not a lot of clear solutions, at least not that I'm able to make out from googling the 'undefined symbol':
http://www.google.com/search?q=_ZN2v816FunctionTemplate3NewEPFNS_6HandleINS_5ValueEEERKNS_9ArgumentsEES3_NS1_INS_9SignatureEEE

Can you recommend any specific versions of node or certain modules that might be more likely to work?

**Comment by charlieroberts** [comment]
Yeah this is a tricky problem. It's discussed here:

https://github.com/rogerwang/node-webkit/issues/872

Apparently you need to install a node module called nw-gyp, and then use that to build the ws module a la:

https://npmjs.org/package/nw-gyp

If you complete the steps in the above link under 'How To Use' hopefully everything will work. It's too bad that this is required... I'd like to figure out a workaround but it will be a while before I'm able to really dig into it.

**Comment by ViktorNova** [comment]
YES, it now works! Here's what I did, for future reference:

As root:

<pre>npm install -g nw-gyp</pre>

Then, in local directories node_modules/ws & node_modules/midi (inside interface.server project dir):

<pre>nw-gyp configure --target=0.7.5 </pre>

(as I am using node-webkit binary v0.75)

Then

<pre>nw-gyp build </pre>

After doing this in midi and ws directories, it works! I'm stoked, thanks so much for pointing me in the right direction. This could be easily fixed with a tiny script, I'd be happy to write one up and test it on a handful of linux platforms and submit it (I had similar issues on 64 bit KXstudio/Ubuntu so that'll be my next test)

=D

**Comment by charlieroberts** [comment]
Great! Thank you for sticking with it and figuring it out! And if you have time to write a script, that would be great. I have somebody who is getting ready to work on documentation / tutorials for course credit, so we should have some new documentation going up in the next month or so and it would be great to include these details along with a script.

This might be useful for OS X as well... I've had a lot of problems dealing with 64-bit MIDI (although not with ws for some reason).

**Comment by plainas** [comment]
Not directly related to this project, but it was this discussion that helped me understand why I was getting so many errors when using some modules. Turns our they need to be rebuilt with node-gyp.
Thank you.

Anyway, you have a typo in your first command. It should be:

`npm install -g nw-gyp`

 (nw-gyp is one word)

**Comment by ViktorNova** [comment]
Ooh, good catch - I fixed it.

Glad it helped ya, it took me forever to figure that out too. Like more than a week!
